### ISSUE TITLE
Dynamic Environments Support

### ISSUE THREAD

**Issue by leoblanc** [fluxcd/helm-operator-get-started#10]
Hello @stefanprodan, we have a new question, please (we are a consulting company trying to promote GitOps and Flux among our clients). [I have posted this question on the Weave Slack, ](https://weave-community.slack.com/archives/C2ND76PAA/p1537551528000100) but didn't receive any feedback yet, so maybe you can help us. 

We are testing the Weave Flux Helm Operator and it's working very well for a "static" configuration, by configuring via yaml files the namespaces (prod, qa, etc), and by also using Yaml to configure [each release](https://github.com/weaveworks/flux-helm-test/blob/master/releases/mariadb_release.yaml). 

Our question is: there is any way to support "dynamic" environments? Suppose that a developer creates a new branch named "app-hot-fix" and push some commits on that branch. The CI process creates new docker images based on that branch. Could be awesome automatically create a new namespace ("app-hot-fix" namespace) for that topic branch and deploy the new Docker image. As far I know, to do that I need to create a new Yaml file to define the namespace, a new Yaml file to define the new release, etc. This configuration process is manual.

But since that branch will just exist for a few hours could be great if that process could be automatically performed by Flux (create the new namespace and release). Something like "GitOps by Convention" (a k8s namespace per Git branch). Are there any features (or tools) that could be used to automagically setup a new release on-the-fly, just based on the existing Git branches? 

Thank you very much in advance!

**Comment by hpurmann** [comment]
This may be the wrong repository as this is just a "getting started" guide.

I recommend creating an issue in the https://github.com/fluxcd/flux repository.

**Comment by leoblanc** [comment]
You are right, closing this one, thanks
