### ISSUE TITLE
adding sealed secret to the repo breaks the bootstrap of the whole

### ISSUE THREAD

**Issue by Morriz** [fluxcd/helm-operator-get-started#20]
Hi, I get the following error when I try to bring up the repo, after adding a sealed secret:

error looking up API resources for SealedSecret.bitnami.com/v1alpha1: not found

How do you deal with resources that don't have their CRDs ready?

**Comment by stefanprodan** [comment]
Flux will retry the sealed secret apply after sealed-secrets chart is deployed.
