### ISSUE TITLE
https://weaveworks.github.io/flux is not a valid chart repository

### ISSUE THREAD

**Issue by jwenz723** [fluxcd/helm-operator-get-started#28]
Running the following command fails:
```
helm repo add fluxcd https://weaveworks.github.io/flux
```
Error:
```
Error: Looks like "https://weaveworks.github.io/flux" is not a valid chart repository or cannot be reached: Failed to fetch https://weaveworks.github.io/flux/index.yaml : 404 Not Found
```

**Comment by jwenz723** [comment]
According to [this](https://github.com/fluxcd/flux/wiki/MoveToFluxCD#2019-07-10-flux-has-moved-house) the repo has moved to https://fluxcd.github.io/flux. Using this URL works for me, but the README needs to be updated.

**Comment by stefanprodan** [comment]
Thanks @jwenz723 for the fix.
