### ISSUE TITLE
Currently we have a releases folder with prod, dev and stage - Can we change it to different clusters

### ISSUE THREAD

**Issue by ctmuthu** [fluxcd/helm-operator-get-started#55]
Let's say I have multiple clusters deployed, and I need to have different release folders for the different clusters. 

Currently, I have created different repositories for different clusters. Now with 2 clusters, it's okay. But with multiple clusters, it would be a mess.

Can you (@stefanprodan ) help me here? Maybe I'm missing something.

**Comment by c4m4** [comment]
you could use a --git-path option in your fluxcd installation

**Comment by ctmuthu** [comment]
Thank you @c4m4
